# Generated by Django 3.1 on 2020-08-30 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200830_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
