# Generated by Django 3.1 on 2020-08-31 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200831_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
