# Generated by Django 3.1 on 2020-08-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_article_article_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='media',
            field=models.URLField(),
        ),
    ]
