# Generated by Django 3.1 on 2020-08-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_article_stored_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='stored_time',
        ),
    ]
