# Generated by Django 3.1 on 2020-08-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_remove_article_stored_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
