# Generated by Django 3.1 on 2020-09-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20200901_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscritptions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.subscription'),
        ),
    ]
