# Generated by Django 3.1 on 2020-09-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20200901_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subscritptions',
            new_name='subscription',
        ),
    ]
